### ISSUE TITLE
ApiFutures::catching with executor does not use executor

### ISSUE THREAD

**Issue by dinsandra** [googleapis/api-common-java#72]
Hello, while trying to understand an issue I was debugging I ended up reading the code for ApiFutures, and I noticed that the passed executor was not used and instead `directExecutor()` was always used. This seems like a bug, so I figured I should report it, terribly sorry if that is not the case.

I would have expected this line to pass the `executor`:
https://github.com/googleapis/api-common-java/blob/master/src/main/java/com/google/api/core/ApiFutures.java#L103

**Comment by sduskis** [comment]
The `ApiFuture` class and other infrastructure uses the same paradigms as Guava, which you can see here: https://github.com/google/guava/wiki/ListenableFutureExplained.  In fact, `ApiFuture` is basically implemented as a wrapped version of `ListenableFuture`.  We use `ApiFuture` because Guava is used everywhere, and we'd like to potentially do things like repackage the underlying `ListenableFuture` implementation so our applications would be compatible with other environments that use an incompatible version of Guava.

The bottom line is that `ApiFuture` works as intended.  The general use starts with an Executor, which will usually spawn a thread to do something interesting.  There are follow up operations once the "interesting" behavior is done.  Transforming the result of the future or doing something with an exceptions are in that "follow up" category.  In most cases, `MoreExecutors.directExecutor()` can be used for the "follow up" operation, since they will be quick.  Guava gives you the option to run the "follow up" on a different thread, just in case you need to.  The cases where you see `directExecutor()` should be fine.

**Comment by dinsandra** [comment]
If the intended behaviour is to always run using a `directExecutor()`, isn't it confusing that the method takes an executor as a parameter that is not used. Wouldn't it be better to not even have that parameter?

**Comment by sduskis** [comment]
oh... I see. I'll change that :).  Sorry for the rant.
